# fly.toml
app = "animated-drawings-patraldo"
primary_region = "qro"

[build]
  dockerfile = "torchserve/Dockerfile"

[deploy]
  strategy = "rolling"
  wait_timeout = "10m"
  release_command = "sleep 90"

[kill]
  signal = "SIGTERM"
  timeout = 30

[[services]]
  processes = ["app"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "60s"
    method = "GET"
    path = "/ping"

  [services.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[mounts]]
  source = "animated_drawings_data"
  destination = "/data"

[[vm]]
  size = "performance-1x"
