# fly.toml
app = "animated-drawings-patraldo"
primary_region = "qro"

[build]
  dockerfile = "torchserve/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop" 
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "60s"
    method = "GET"
    path = "/ping"

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory = "4gb"

[deploy]
  strategy = "rolling"
  wait_timeout = "10m"
  release_command = "sleep 90"

kill_signal = "SIGTERM"
kill_timeout = 30
